/**
 * generated by Xtext
 */
package eu.paasage.camel.dsl.validation;

import eu.paasage.camel.dsl.validation.AbstractCamelDslValidator;
import org.eclipse.xtext.validation.Check;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class CamelDslValidator extends AbstractCamelDslValidator {
  public static int counter = 0;
  
  @Check
  public void checkCamelModelBeforeFurtherValidation(final /* CamelModel */Object cm) {
    throw new Error("Unresolved compilation problems:"
      + "\nDeploymentElement cannot be resolved to a type."
      + "\neResource cannot be resolved"
      + "\nresourceSet cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nallContents cannot be resolved"
      + "\nhasNext cannot be resolved"
      + "\nnext cannot be resolved"
      + "\nname cannot be resolved"
      + "\n== cannot be resolved"
      + "\nname cannot be resolved"
      + "\neClass cannot be resolved"
      + "\nname cannot be resolved"
      + "\n+ cannot be resolved");
  }
  
  public final static String INVALID_NAME = "invalidName";
  
  public final static String INVALID_FEATURE = "invalidFeature";
  
  public final static String INVALID_CARDINALITY = "invalidCardinality";
  
  public final static String INVALID_VALUE = "invalidValue";
  
  public final static String INVALID_ATTRIBUTE = "invalidAttribute";
  
  public final static String INVALID_ATTRIBUTE_VALUE = "invalidAttributeValue";
  
  @Check
  public void checkProviderModelName(final /* ProviderModel */Object model) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field CamelPackage is undefined for the type CamelDslValidator"
      + "\nname cannot be resolved"
      + "\n== cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nMODEL__NAME cannot be resolved");
  }
  
  @Check
  public void checkRootFeature(final /* ProviderModel */Object model) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field ProviderPackage is undefined for the type CamelDslValidator"
      + "\nname cannot be resolved"
      + "\n!= cannot be resolved"
      + "\n&& cannot be resolved"
      + "\nrootFeature cannot be resolved"
      + "\n== cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nPROVIDER_MODEL__ROOT_FEATURE cannot be resolved");
  }
  
  @Check
  public void checkFeatureName(final /* Feature */Object feature) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field ProviderPackage is undefined for the type CamelDslValidator"
      + "\nname cannot be resolved"
      + "\n== cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nFEATURE__NAME cannot be resolved");
  }
  
  @Check
  public void checkFeatureCardinality(final /* Feature */Object feature) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field ProviderPackage is undefined for the type CamelDslValidator"
      + "\nname cannot be resolved"
      + "\n!= cannot be resolved"
      + "\n&& cannot be resolved"
      + "\nfeatureCardinality cannot be resolved"
      + "\n== cannot be resolved"
      + "\nname cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nFEATURE__FEATURE_CARDINALITY cannot be resolved");
  }
  
  @Check
  public void checkFeatureCardinalityMinMax(final /* Feature */Object feature) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field ProviderPackage is undefined for the type CamelDslValidator"
      + "\nname cannot be resolved"
      + "\n!= cannot be resolved"
      + "\n&& cannot be resolved"
      + "\nfeatureCardinality cannot be resolved"
      + "\n!= cannot be resolved"
      + "\nfeatureCardinality cannot be resolved"
      + "\ncardinalityMin cannot be resolved"
      + "\n> cannot be resolved"
      + "\nfeatureCardinality cannot be resolved"
      + "\ncardinalityMax cannot be resolved"
      + "\nname cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nFEATURE__FEATURE_CARDINALITY cannot be resolved");
  }
  
  @Check
  public void checkAttributeName(final /* Attribute */Object attribute) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field ProviderPackage is undefined for the type CamelDslValidator"
      + "\nname cannot be resolved"
      + "\n== cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nATTRIBUTE__NAME cannot be resolved");
  }
  
  @Check
  public void checkAttributeValue(final /* Attribute */Object attribute) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field ProviderPackage is undefined for the type CamelDslValidator"
      + "\nname cannot be resolved"
      + "\n!= cannot be resolved"
      + "\n&& cannot be resolved"
      + "\nvalue cannot be resolved"
      + "\n== cannot be resolved"
      + "\n&& cannot be resolved"
      + "\nvalueType cannot be resolved"
      + "\n== cannot be resolved"
      + "\nname cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nATTRIBUTE__VALUE cannot be resolved");
  }
  
  @Check
  public void checkConstraint(final /* Constraint */Object constraint) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field ProviderPackage is undefined for the type CamelDslValidator"
      + "\nThe method or field ProviderPackage is undefined for the type CamelDslValidator"
      + "\nThe method or field ProviderPackage is undefined for the type CamelDslValidator"
      + "\nname cannot be resolved"
      + "\n== cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nCONSTRAINT__NAME cannot be resolved"
      + "\nfrom cannot be resolved"
      + "\n== cannot be resolved"
      + "\nname cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nCONSTRAINT__FROM cannot be resolved"
      + "\nto cannot be resolved"
      + "\n== cannot be resolved"
      + "\nname cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nCONSTRAINT__TO cannot be resolved");
  }
  
  @Check
  public void checkAttributeConstraint(final /* AttributeConstraint */Object ac) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field ProviderPackage is undefined for the type CamelDslValidator"
      + "\nThe method or field ProviderPackage is undefined for the type CamelDslValidator"
      + "\nThe method or field ProviderPackage is undefined for the type CamelDslValidator"
      + "\nThe method or field ProviderPackage is undefined for the type CamelDslValidator"
      + "\nfrom cannot be resolved"
      + "\n== cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nATTRIBUTE_CONSTRAINT__FROM cannot be resolved"
      + "\nto cannot be resolved"
      + "\n== cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nATTRIBUTE_CONSTRAINT__TO cannot be resolved"
      + "\nfromValue cannot be resolved"
      + "\n== cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nATTRIBUTE_CONSTRAINT__FROM_VALUE cannot be resolved"
      + "\ntoValue cannot be resolved"
      + "\n== cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nATTRIBUTE_CONSTRAINT__TO_VALUE cannot be resolved");
  }
}
