/**
 * generated by Xtext
 */
package eu.paasage.camel.dsl.serializer;

import eu.paasage.camel.dsl.serializer.AbstractCamelDslSyntacticSequencer;

@SuppressWarnings("all")
public class CamelDslSyntacticSequencer extends AbstractCamelDslSyntacticSequencer {
}
