/**
 * generated by Xtext
 */
package eu.paasage.camel.dsl.serializer;

import eu.paasage.camel.dsl.serializer.AbstractCamelDslSemanticSequencer;

@SuppressWarnings("all")
public class CamelDslSemanticSequencer extends AbstractCamelDslSemanticSequencer {
}
