/*
 * generated by Xtext
 */
package eu.paasage.camel.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import eu.paasage.camel.dsl.services.CamelDslGrammarAccess;

public class CamelDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CamelDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected eu.paasage.camel.dsl.parser.antlr.internal.InternalCamelDslParser createParser(XtextTokenStream stream) {
		return new eu.paasage.camel.dsl.parser.antlr.internal.InternalCamelDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "CamelModel";
	}
	
	public CamelDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CamelDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
