/*
* generated by Xtext
*/
package eu.paasage.camel.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CamelDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("eu/paasage/camel/dsl/parser/antlr/internal/InternalCamelDsl.tokens");
	}
}
