/*
 * generated by Xtext
 */
package eu.paasage.camel.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CamelDslUiModule extends eu.paasage.camel.dsl.ui.AbstractCamelDslUiModule {
	public CamelDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
