/*
 * generated by Xtext
 */
package eu.paasage.camel.dsl.ui.contentassist

import eu.paasage.camel.dsl.ui.contentassist.AbstractCamelDslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class CamelDslProposalProvider extends AbstractCamelDslProposalProvider {
}
