/*
 * generated by Xtext
 */
package eu.paasage.camel.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import eu.paasage.camel.dsl.ui.internal.CamelDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CamelDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CamelDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CamelDslActivator.getInstance().getInjector(CamelDslActivator.EU_PAASAGE_CAMEL_DSL_CAMELDSL);
	}
	
}
