/*
 * generated by Xtext
 */
package eu.paasage.camel.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CamelDslStandaloneSetup extends CamelDslStandaloneSetupGenerated{

	public static void doSetup() {
		new CamelDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

