/*
 * generated by Xtext
 */
package eu.paasage.camel.dsl;

import eu.paasage.camel.dsl.scoping.CamelQualifiedNameProvider;

import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.parsetree.reconstr.ITransientValueService;
import org.eclipse.xtext.parsetree.reconstr.impl.ValueSerializer;
import org.eclipse.xtext.serializer.sequencer.TransientValueService;
import org.eclipse.xtext.validation.CompositeEValidator;

import com.google.inject.Binder;
import com.google.inject.name.Names;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CamelDslRuntimeModule extends eu.paasage.camel.dsl.AbstractCamelDslRuntimeModule {
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
        return CamelQualifiedNameProvider.class;
    }
}
