/*
 * generated by Xtext
 */
package eu.paasage.camel.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.ComposedChecks;

@ComposedChecks(validators= {org.eclipse.xtext.validation.ImportUriValidator.class})
public class AbstractCamelDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.paasage.eu/2015/06/camel"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.paasage.eu/2015/06/camel/deployment"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.paasage.eu/2015/06/camel/execution"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.paasage.eu/2015/06/camel/location"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.paasage.eu/2015/06/camel/metric"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.paasage.eu/2015/06/camel/organisation"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.paasage.eu/2015/06/camel/provider"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.paasage.eu/2015/06/camel/type"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.paasage.eu/2015/06/camel/requirement"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.paasage.eu/2015/06/camel/scalability"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.paasage.eu/2015/06/camel/security"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.paasage.eu/2015/06/camel/unit"));
		return result;
	}
}
